# Generated by Django 5.2.16 on 2026-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Betreff"
                    ),
                ),
                ("message", models.TextField(verbose_name="Nachricht")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingegangen am"
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
            ],
            options={
                "verbose_name": "Kontaktanfrage",
                "verbose_name_plural": "Kontaktanfragen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Vorname"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nachname"),
                ),
                (
                    "street",
                    models.CharField(max_length=200, verbose_name="Straße, Hausnummer"),
                ),
                ("postal_code", models.CharField(max_length=10, verbose_name="PLZ")),
                ("city", models.CharField(max_length=100, verbose_name="Ort")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Mail")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geburtsdatum"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Anmerkungen")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingegangen am"
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
            ],
            options={
                "verbose_name": "Aufnahmeantrag",
                "verbose_name_plural": "Aufnahmeanträge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Interner Bezeichner, z. B. 'impressum', 'satzung', 'kontakt'.",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="HTML ist erlaubt (z. B. <p>, <h2>, <ul>, <a>).",
                        verbose_name="Inhalt",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Optionales Dokument zum Download, z. B. Satzung oder Aufnahmeantrag als PDF.",
                        null=True,
                        upload_to="documents/",
                        verbose_name="Dokument (PDF)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt geändert"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seite",
                "verbose_name_plural": "Seiten",
                "ordering": ["slug"],
            },
        ),
    ]
