# Generated by Django 5.2.16 on 2026-08-03 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=110, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Reihenfolge"),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=160, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breitengrad",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Längengrad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ort",
                "verbose_name_plural": "Orte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vorname"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nachname"),
                ),
                (
                    "maiden_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Geburtsname"
                    ),
                ),
                (
                    "birth_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Geburtsjahr"
                    ),
                ),
                (
                    "death_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Sterbejahr"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Anmerkungen")),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="photos/%Y/%m/", verbose_name="Bild"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="Datum von"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="Datum bis"),
                ),
                (
                    "date_text",
                    models.CharField(
                        blank=True,
                        help_text="Frei formulierte Datierung, z. B. 'um 1930' oder '1950er Jahre'.",
                        max_length=100,
                        verbose_name="Datierung (Text)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Fotograf, Nachlass, Privatbesitz.",
                        max_length=255,
                        verbose_name="Quelle / Bildrechte",
                    ),
                ),
                (
                    "inventory_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Inventarnummer"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Nur veröffentlichte Fotos sind auf der öffentlichen Seite sichtbar.",
                        verbose_name="Veröffentlicht",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hochgeladen am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt geändert"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="archive.category",
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="archive.location",
                        verbose_name="Ort",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hochgeladen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto",
                "verbose_name_plural": "Fotos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoPersonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Horizontale Position auf dem Bild in Prozent (0-100), optional.",
                        max_digits=5,
                        null=True,
                        verbose_name="Position X (%)",
                    ),
                ),
                (
                    "y_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vertikale Position auf dem Bild in Prozent (0-100), optional.",
                        max_digits=5,
                        null=True,
                        verbose_name="Position Y (%)",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="z. B. 'hintere Reihe, 3. von links'.",
                        max_length=200,
                        verbose_name="Anmerkung",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Freigegeben"),
                            ("pending", "Ausstehend"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="approved",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="archive.person",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_tags",
                        to="archive.photo",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geprüft von",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vorgeschlagen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personen-Markierung",
                "verbose_name_plural": "Personen-Markierungen",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="persons",
            field=models.ManyToManyField(
                blank=True,
                related_name="photos",
                through="archive.PhotoPersonTag",
                to="archive.person",
                verbose_name="Personen",
            ),
        ),
        migrations.AddConstraint(
            model_name="photopersontag",
            constraint=models.UniqueConstraint(
                fields=("photo", "person"), name="unique_person_per_photo"
            ),
        ),
    ]
